/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://2n2sh6c5kbamtds6vinpzyns34.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-kba4s3p3abf3rklol5dspmw3xm",
    "aws_cognito_identity_pool_id": "us-east-1:b9e25482-7e71-41a8-b848-f3149209677a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_JM9iMWZI1",
    "aws_user_pools_web_client_id": "3qmr2oljtas509i1f8o7tbmodl",
    "oauth": {}
};


export default awsmobile;
